### ISSUE TITLE
"center but left justified" sometimes does not work

### ISSUE THREAD

**Issue by ijgnd** [ankipalace/anki-wrapper#1]
First of all: Thanks for sharing this add-on.

When I use the button to "center but left justified" some text sometimes the underlying html is not changed and no divs with classes are applied/inserted.

I tested with Anki 2.1.26 (downloaded from apps.ankiweb.net) in linux with only your add-on installed that I downloaded today. I used a new profile and use the default config of your add-on. 

I attached a screencast that shows my setup and an example of text (and its html source code) that is not transformed.

![](https://raw.githubusercontent.com/ijgnd/anki__help/master/screenshots/wrapper.gif)

Did I miss something? If it's a bug do you need additional info?

PS: I'm not the one who downvoted on ankiweb.

**Comment by epiphanie-gedeon** [comment]
Hi,
Thanks for your appreciation :)

This behavior was tentatively documented in the readme, though it should be extended upon and explain that it only works on whole paragraph and not part of it.
The wrap method is part of anki, and is designed to identify if the current selection is a paragraph or just a part of it, and fails to manipulate a part of a sentence like an entire paragraph.

For instance, if you instead use ``<b></b>`` to wrap the text, then it does behave correctly in your example.

Should the addon isolate the part of text as a new paragraph? Or should it rather act on the whole selected paragraph?

That is, if we have ``It only work for some text`` and use it on ``some text`` should it act on the whole ``It only work for some text`` or should it separate them instead? 

Thank you for the detailed report!

**Comment by ijgnd** [comment]
Thanks for the quick reply.

Upon rereading I also noticed/understood the "Does not work on part of sentences" ... Maybe just make this much more prominent?

> Should the addon isolate the part of text as a new paragraph? Or should it rather act on the whole selected paragraph?

But I very much prefer creating a new paragraph just from the selection:  Users are (which probably means "I am") accustomed to commands only affecting a selection? It's quicker to manually select a whole paragraph than manually inserting two line breaks. But I'm not that good about anticipating what other users like. Maybe just add a tooltip if the changes aren't applied?

**Comment by epiphanie-gedeon** [comment]
You're definitely right that it should just isolate the selected paragraph, it does seem to make the most sense.
I'm trying to test the wrap function of the anki addon to see if it can be modified, and if all come to worst, I'll just copy some part of it. Will do that today/tomorow, along with a small js refactoration
