### ISSUE TITLE
There was a problem with the provided configuration: ⁨'alt+]' does not match

### ISSUE THREAD

**Issue by okerivy** [ankipalace/anki-wrapper#5]
Unable to use shortcut keys `alt+]`
An error ：There was a problem with the provided configuration: ⁨'alt+]' does not match

macos anki 2.1.49

---
```
"unQuotesa": {
         "action": "unwrap",
        "beginWrap": "「",
        "endWrap": "」",
        "style": {
             "icon": "uncloze.png",
             "keys": "alt+]",
            "tip": "unQuotesa「」"
        }
},
```

---
<img width="673" alt="Snipaste_2022-01-12_15-12-34" src="https://user-images.githubusercontent.com/4578474/149080819-cb2e00de-d163-4161-b69d-af1c8935375d.png">

---

**Comment by AnKingMed** [comment]
I think depending on the addons you have or other computer programs, certain shortcuts won't work. You'll need to try something else
