### ISSUE TITLE
GIANT button image on 2.1.53

### ISSUE THREAD

**Issue by AnKingMed** [ankipalace/anki-wrapper#8]
@BlueGreenMagick or @RisingOrange are you able to look into this?  I can post for Damien as well if it's better corrected from his end

![image](https://user-images.githubusercontent.com/57678116/170851697-9462da6f-965e-45aa-99af-b05258b415c6.png)

**Comment by RisingOrange** [comment]
I just tested it on 2.1.53 and the size of the icon was normal. This probably happens because of some other add-on.

**Comment by AnKingMed** [comment]
Looks like this fixed it!
