### ISSUE TITLE
Please add a shortcut for the button center but justified left

### ISSUE THREAD

**Issue by ankidoc** [ankipalace/anki-wrapper#9]
Please add a shortcut for the button center but justified left

that would be so great because you could combine it with bettertouchtools after selecting some text and saves huge time.

and is there any possibility to use the wrapper meta add on with the addon edit during review cloze? As far as I tried only the usual center, left, right works. there is "justify" too but it does not work with like your add on in the editor when you push center after that.

Thanks! 

great add on!

**Comment by AnKingMed** [comment]
This was added
